### ISSUE TITLE
idea for "issues with calico"

### ISSUE THREAD

**Issue by networkop** [danderson/metallb#421]
One way to establish an extra BGP session by MetalLB is to source it from a loopback. With Calico, you can [add/remove](https://docs.projectcalico.org/v3.6/networking/changing-ip-pools#example-kubernetes) IP pools that are being advertised.  So here's an idea (i haven't tested it though):
1. MetalLB creates a new loopback on every node
2. The /32 IP of that loopback is added to calico advertised pools
3. MetalLB established a BGP sessions sourced from that loopback IP

From the POV of the TOR switch, this will look like two BGP sessions, one established over a recursively resolved nexthop

**Comment by z3net** [comment]
The cleanest solution I think is to bgp peer calico to the TOR L3 switch, and bgp peer metallb to the upstream router.

**Comment by gclawes** [comment]
There's also indication that metallb works if you peer it locally with calico and supply an `IPPool` to calico: https://github.com/danderson/metallb/issues/114#issuecomment-469985074

I've got this working on my local single-machine dev environment with calico v3.5, no idea if it works in other situations:
https://gitlab.com/gclawes/enterprise-kubernetes/blob/master/helm/metallb-values.yaml
https://gitlab.com/gclawes/enterprise-kubernetes/blob/master/calico/bgp-configuration.yaml#L18

**Comment by kfox1111** [comment]
Could the worker node run a new aggregater and have both canal and metallb talk to the local one?

**Comment by gclawes** [comment]
I don't even think that's necessary.  `metallb -> calico-node -> upstream router` seems to be working in my config, both metallb and calico pod announcements get through to the upstream router.  Not sure how canal works, though.

**Comment by eknudtson** [comment]
We've bypassed calico entirely by using FRR and layer 3 routing to the host (hosts function as routers w/ BGP unnumbered peering to TOR leaves).  We run Calico in policy-only mode and let FRR advertise pod IPs.

For metallb, we set it to use pod networking, then have it peer with the host local FRR using BGP dynamic peers along with an entry for each worker in the metallb configmap.  Because FRR's dynamic peering is listening for a host w/ an external ASN, the peering is setup automatically once the host entry in the configmap is in place.

A bit of work on the configmap side to keep workers up to date, but it works flawlessly (we've run this in production for several months).

**Comment by hightoxicity** [comment]
For me everything is properly working if I patch the bird template on node specific peers (since this is the one I use) and I do the following:

`
    # ------------- Node-specific peers -------------
    {{$node_peers_key := printf "/host/%s/peer_v4" (getenv "NODENAME")}}
    {{if ls $node_peers_key}}
    {{range gets (printf "%s/*" $node_peers_key)}}{{$data := json .Value}}
    {{$nums := split $data.ip "."}}{{$id := join $nums "_"}}
    # For peer {{.Key}}
    {{- if eq $data.ip ($node_ip) }}
    # Skipping ourselves ({{$node_ip}})
    {{- else}}
    protocol bgp Node_{{$id}} from bgp_template {
    {{- if eq $data.ip ("127.0.0.1")}}
      passive on; # Don't talk to yourself
      local as {{$data.as_num}};
    {{- end}}
      neighbor {{$data.ip}} as {{$data.as_num}};
    {{- if and (eq $data.as_num $node_as_num) (ne "" ($node_cluster_id)) (ne $data.rr_cluster_id ($node_cluster_id))}}
      rr client;
      rr cluster id {{$node_cluster_id}};
    {{- end}}
    }
    {{- end}}
    {{end}}
    {{else}}# No node-specific peers configured.{{end}}
    {{end}}{{/* End of IPv4 enable check */}}
`
=> passive on;
=> local as {{$data.as_num}};

**Comment by danderson** [comment]
From my perspective, this is Calico's problem to solve, not MetalLB's. In the other bug, there seemed to be agreement for adding an option for BGP passive mode in Calico, but nobody's interested in writing the patch yet. I suggest taking the discussion there so that Calico folks can also comment on ideas.

**Comment by hightoxicity** [comment]
> From my perspective, this is Calico's problem to solve, not MetalLB's. In the other bug, there seemed to be agreement for adding an option for BGP passive mode in Calico, but nobody's interested in writing the patch yet. I suggest taking the discussion there so that Calico folks can also comment on ideas.

That 's true calico is missing a passive feature on BGPPeer... But another thing is missing...
It is metallb that knows about which pod deal with which IP, for my setup and with externalTrafficPolicy: Local, I think the kube node is currently missing the route to the pod network namespace (this would permit to bird to not set it as unreachable) and this is what is doing calico with its floating_ip feature.
