### ISSUE TITLE
Metal LB L2 Doesn't support different subnet from Node Subnet?

### ISSUE THREAD

**Issue by dtalbott** [danderson/metallb#433]
Hi,

We have setup a Metal LB configuration that is using L2 with the expected IP range for the Services of 10.120.50.32 -- 10.120.50.46. The K8S host nodes are in a subnet of 10.120.52.0/24. When we try to bring up the services with this configuration we get the following in the logs:

{"caller":"main.go:231","event":"endUpdate","msg":"end of service update","service":"default/nginx","ts":"2019-04-30T16:31:12.313383588Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"default/service1","ts":"2019-04-30T16:31:12.313432991Z"}
{"caller":"main.go:229","event":"serviceAnnounced","ip":"10.120.50.32","msg":"service has IP, announcing","pool":"my-ip-space","protocol":"layer2","service":"default/service1","ts":"2019-04-30T16:31:12.313499851Z"}
{"caller":"main.go:231","event":"endUpdate","msg":"end of service update","service":"default/service1","ts":"2019-04-30T16:31:12.313563061Z"}
{"caller":"main.go:185","error":"assigned IP not allowed by config","ip":"10.120.52.42","msg":"IP allocated by controller not allowed by config","op":"setBalancer","service":"default/service1","ts":"2019-04-30T16:31:09.836280503Z"}
{"caller":"main.go:186","event":"endUpdate","msg":"end of service update","service":"default/service1","ts":"2019-04-30T16:31:09.836304077Z"}

and we never get the ARP requestsand thus, there is no connectivity externally to these services...

When we configure it to use a range in the same .52.0/24 subnet, this all works as expected, it gets assigned, ARPs, and we can connect from external nodes.

Now reading a bit more into the code and log message there, I noticed that the message indicates that it still was assigned a .52 IP subnet despite asking for an IP in the .50 subnet and because they mismatched, the service is destroyed. That makes sense... but not sure why are we getting an IP in the wrong pool.

Therefore, couple of questions:

1.   Is this a known issue/limitation or just our setup? -- seems like this should be do-able
2.  What determines the Pool's available IPs in Layer 2 (if not the config map)?
3.  Is there a configuration necessary to use different subnets other than the K8S' Hosts

Any help is greatly appreciated.

Thanks!

**Comment by ohauer** [comment]
With L2 and having Services not on the same network as the nodes you have to setup your own static routing on your network.
e.g. 

1 - Node IP 10.120.52.10
2 - Service IP : 10.120.50.20

- on cisco switch
   ip route 10.120.50.20 255.255.255.255 10.120.52.10
 
 - on comware switch
   ip route-static 10.120.50.20 32 10.120.52.10
 
 - on a windows system (works only if you are in the 10.120.52.x subnet)
   route add -4 10.120.50.20 mask 255.255.255.255 10.120.52.10

But in case the service is moved to a different node you have to adjust the routing again.

**Comment by aleks-mariusz** [comment]
i considered how i too would run into this issue when trying to set up a kubernetes cluster with nodes that span different subnets.. ultimately i feel that using the L2 mode is *not* going to be possible, since the IP services are could not be on either subnet for them to be reacher from the greater network.. i think this is a usecase you pretty much have to turn to the BGP mode (and have that separate subnet be reachable based on routing decisions at L3 of the upstream routers, which get fed their information ala BGP via metallb)

**Comment by danderson** [comment]
This is just "how networks work". In L2 mode, the rest of the network has to know where the subnet is located, so that the machines know when they should forward packets via a router, or when they should make ARP requests to find a machine on the local ethernet segment.

Basically, to use an IP range for k8s service IPs, the rest of the network (non-k8s machines, routers, ...) must be configured just like if you had regular machines with those IPs.

I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack.
