### ISSUE TITLE
Feature request; Support for dual-stack in the controller

### ISSUE THREAD

**Issue by uablrek** [danderson/metallb#464]
## Background

Support for ipv4/ipv6 dual-stack as described in the dual-stack [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20180612-ipv4-ipv6-dual-stack.md) is well on it's way. [Phase 1](https://github.com/kubernetes/kubernetes/pull/73977) is already merged and will be in k8s 1.16. Phase 2 is partially implemented in PR https://github.com/kubernetes/kubernetes/pull/79386 which is currently under review. With this PR in place the services will have a new attribute `serviceIPFamily` which defines the ip family. Example;
```
apiVersion: v1
kind: Service
metadata:
  name: mconnect-ipv6
spec:
  ipFamily: IPv6
  selector:
    app: mconnect
  ports:
  - port: 5001
  type: LoadBalancer
```
The `serviceIPFamily` can have values (names may change after the review);
* Default
* IPv6
* IPv4

The `ClusterIP` will be assigned from the selected family.

## Feature request

The metallb `controller` must be extended to maintain pools for both ipv4 and ipv6 and assign `loadBalancerIP` depending on family of the `ClusterIP` (the `serviceIPFamily` should not be examined).

I know this issue is "ahead of time" but work can start now to be prepared when dual-stack is released in alpha. I think there are many `metallb` users that want to try dual-stack early (I am one).

I think the `controller` and `speaker` should be handled independently for dual-stack support. Also I think L2 and BGP mode in the `speaker` shall be handled independently. Dual-stack for L2 is probably not too difficult, but BGP in `metallb` does not currently support ipv6 so it will be a much harder task.

**Comment by uablrek** [comment]
The `controller` is "family agnostic". It assigns ipv6 addresses if the pool is ipv6, even in an ipv4-only cluster;
```
# kubectl get svc
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
coredns        ClusterIP      12.0.0.2       <none>        53/UDP,53/TCP    31s
kubernetes     ClusterIP      12.0.0.1       <none>        443/TCP          32s
mconnect       LoadBalancer   12.0.38.207    1000::        5001:31457/TCP   7s
```
This is not a bug and is very good for implementing dual-stack support.

**Comment by danderson** [comment]
Huge thank you for investigating how dual-stack support can work with MetalLB! This is exciting, I've wanted this feature since day 1 of MetalLB :)

## Design

The design on the k8s side is interesting: I expected that 1 service could have multiple address families. In fact, if the KEP says 1 service == 1 family, that is _much_ easier to implement in MetalLB, because we don't have to keep track of multiple assigned IPs. That's great!

I'm curious why you say `assign loadBalancerIP depending on family of the ClusterIP (the serviceIPFamily should not be examined).`. Why should we use the `ClusterIP` instead of the `serviceIPFamily`? I'm sure I'm just missing something obvious :)

I 100% agree with your implementation phases.

### Controller

I see you've made great progress on the controller, I'll review that in a moment. I'm amused that right now, we assign an IPv6 LB IP even if the cluster is IPv4... I guess I didn't think about what happens if someone configures the controller like that :D

### Speaker L2

L2 in the speaker... In theory it _should_ just work! We already support NDP (IPv6's equivalent of ARP), and all the logic is there so the speaker _should_ just go "oh, this is a v6 address, I'll use NDP!". Of course, the problem is, I haven't tested any of this and I still don't have automated testing, so there's probably some bugs here or there :).

### Speaker BGP

BGP, we're missing a fairly big chunk. I _think_ we can establish IPv6 BGP sessions at the TCP layer (i.e. announce IPv4 prefixes on a BGP session that's running over TCPv6). However, we do _not_ have an implementation of MP-BGP address encoding. We tell the peer that we support v4 and v6 advertisements (because Quagga requires it)... But we use the "legacy" IP encoding format that only supports IPv4.

So, for BGP, the main work is implementing the message encoding described in https://tools.ietf.org/html/rfc4760 , and replacing the existing BGP message encoding completely (the RFC4760 format can express IPv4 and IPv6 addrs). And then there's probably a long tail of extra work to do elsewhere in the BGP stack, e.g. to correctly group IPs by family during announcements. I'm not actually sure about that, it depends a bit on the details of the RFC.

**Comment by danderson** [comment]
Another quick note: someone contacted me on Twitter and offered to implement MP-BGP. I need to get in touch with them and see if they're still interested, but that _might_ be WIP as well!

**Comment by uablrek** [comment]
The reason for not using `serviceIPFamily` is that we don't know the "Default" family. Not even `kube-proxy` knows it (at least not currently). I am working with dual-stack support for proxy-mode=ipvs and discussed it on [slack](https://kubernetes.slack.com/archives/CGF3A900N/p1565812069098000).

**Comment by uablrek** [comment]
I made a PR on ipv6-bgp some time ago; https://github.com/danderson/metallb/pull/329

The slogan is misleading, it is really a bgp-mp implementation. The structure may not be feasible, but the bit-manipulations for bgp can maybe be reused (it takes some time and `tcpdump`'ing to get right).

**Comment by danderson** [comment]
Aah, of course, I didn't think of the default family! It's a little bit weird I guess that we can't know what the service config means until some other controller does something... But oh well :). Okay, using ClusterIP makes sense then.

Oh right, your PR did some MP-BGP! Yes, the code in that PR will probably help a bunch. I feel bad for abandoning it like I did :(. Would you prefer to pick up that BGP PR again yourself, or focus on the controller and other parts of dual-stack? I have a volunteer for the MP-BGP stuff, and they can reuse your bit-twiddling functions, if you're okay with that.

**Comment by uablrek** [comment]
And using ClusterIP makes the controller PR independent of the dual-stack PRs in k8s, so it can be merged anytime. Ahead of 1.16 even :smile: 

> I feel bad for abandoning it like I did :(

No worries :smile:  I enjoyed working with it. It was fun to do some protocol stuff again and I got to learn about BGB. We got requirements on BFD and other things that forced us to to a separate BGP thing anyway in the end.

I rather focus on the `controller` since we can't use the BGP part of `speaker` anyway. If I can find the time I will just start L2 with dual-stack and see if it works out-of-the-box.

**Comment by uablrek** [comment]
> L2 in the speaker... In theory it should just work! 

It does :grin:

I used the (updated) manifests in the PR #466 and it just works as you said!

See more info in the PR #466.

So when k8s dual-stack is released, `metallb` will be ready for it :smiley:
